#!/bin/sh
#
# PROVIDE: xapsd
# REQUIRE: LOGIN cleanvar dovecot
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf[.local] to enable xaps:
# xapsd_enable="YES"
#

. /etc/rc.subr

name="xapsd"
rcvar=${name}_enable

load_rc_config $name


#defaults
: ${xapsd_enable="NO"}
: ${xapsd_cmd="/usr/local/bin/xapsd"}
: ${xapsd_log="/var/log/xapsd.log"}
: ${xapsd_pidfile="/var/run/xapsd/xapsd.pid"}
#: ${xapsd_configpath="/usr/local/etc/xapsd"}
#: ${xapsd_configname="xapsd.yaml"}

#xapsd_args="-configPath ${xapsd_configpath} -configName ${xapsd_configname}"
xapsd_args=""

pidfile=${xapsd_pidfile}
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -r -f -m 3 -o ${xapsd_log} ${xapsd_cmd} ${xapsd_args}"

run_rc_command "$1"
